version: '3'

networks:
  default:
    name: backend

volumes:
  synthea-data:
  messages:

services:

  gs-etl:
    image: gs-etl
    container_name: gs-etl
    build:
      context: gs-etl
      dockerfile: Dockerfile
    volumes:
      - synthea-data:/input
      - messages:/messages

  synthea:
    image: synthea
    container_name: synthea
    build:
      context: synthea
      dockerfile: Dockerfile
      args:
        SYNTHEA_BRANCH: "${SYNTHEA_BRANCH:-master-branch-latest}"
        SYNTHEA_FILE: "${SYNTHEA_FILE:-synthea-with-dependencies}"
    environment:
      NUMBER_OF_RECORDS: 500
    volumes:
      - synthea-data:/output/csv
      - messages:/messages