version: '3'

networks:
  default:
    name: backend

volumes:
  synthea-data:
  messages:

services:

  gs-etl:
    image: gs-etl
    container_name: gs-etl
    build:
      context: gs-etl
      dockerfile: Dockerfile
    environment:
      - GCS_PATH=synthea
      - BUCKET_NAME=aou-curation-omop-dev_transfer_fhir
    volumes:
      - synthea-data:/input
      - messages:/messages

  synthea:
    image: synthea
    container_name: synthea
    build:
      context: synthea
      dockerfile: Dockerfile
      args:
        SYNTHEA_BRANCH: "${SYNTHEA_BRANCH:-master-branch-latest}"
        SYNTHEA_FILE: "${SYNTHEA_FILE:-synthea-with-dependencies}"
    environment:
      CSV: "True"
      CCDA: "True"
      DSTU2: "True"
      STU3: "True"
      R4: "True"
      NUMBER_OF_RECORDS: 5
    volumes:
      - synthea-data:/output
      - messages:/messages